name: "Gradle Wrapper"

on:
  pull_request:
    branches:
      - main

jobs:
  validation:
    name: "Validate"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.example }}
    strategy:
      matrix:
        example: [ android, code-samples/ARBlackPanther, code-samples/ARHelloWorldAndroid, code-samples/ARPlacingObjects, code-samples/ARRetail, code-samples/ARTesla ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1